### ISSUE TITLE
How to add accuracy into the training process

### ISSUE THREAD

**Issue by Nine9844** [jeya-maria-jose/UNeXt-pytorch#1]
I want to add the accuracy calculation in the training process, but I can't, can you tell me how to add it? thank you

**Comment by jeya-maria-jose** [comment]
Hi, the current version of the code will print IoU. You should be able to add dice score also easily.

**Comment by Nine9844** [comment]
Thank you very much for your help and wish you the best of luck in your studies





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeya-maria-jose/UNeXt-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeya-maria-jose/UNeXt-pytorch] How to add accuracy into the training process (Issue #1)





 
Hi, the current version of the code will print IoU. You should be able to add dice score also easily.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
