### ISSUE TITLE
Parameter Settings on BUSI dataset

### ISSUE THREAD

**Issue by xiaohancl** [jeya-maria-jose/UNeXt-pytorch#12]
Can you share your parameter Settings on the breast ultrasound image dataset?I set the epoch=400, batch-size=8, lr=0.0001,momentum=0.9,optimzer=adam and scheduler=CosineAnnealingLR  and channels setting as [16, 32, 128, 160, 256],but got the result:Dice:75.74         IOU:61.99(In the paper, it's 66.95 )
Thanks！

**Comment by guangguangLi** [comment]
ValueError: Target size (torch.Size([16, 3, 256, 256])) must be the same as input size (torch.Size([16, 1, 256, 256]))
I also use the BUSI dataset, do you know how to fix the above error?

**Comment by jeya-maria-jose** [comment]
Hi @xiaohancl , I just rechecked and I am able to get the reported performance in the paper. The settings you used are correct but did you resize the images to 256? Also, for the experiments on BUSI dataset, we only considered the benign and mailgnant images resulting in a total of 647 images.

**Comment by jeya-maria-jose** [comment]
Hi @guangguangLi , which line are you getting the error?

**Comment by xiaohancl** [comment]
> Hi @xiaohancl , I just rechecked and I am able to get the reported performance in the paper. The settings you used are correct but did you resize the images to 256? Also, for the experiments on BUSI dataset, we only considered the benign and mailgnant images resulting in a total of 647 images.

i have resized the images to 256 by the train_transform and val_transform acording to your source code. Busi dataset is also downloaded following the [link](https://www.kaggle.com/aryashah2k/breast-ultrasound-images-dataset) you provided. And then put the 647 images in the inputs/busi/images and put the 647 masks in the inputs/busi/masks/0

**Comment by xiaohancl** [comment]
> > Hi @xiaohancl , I just rechecked and I am able to get the reported performance in the paper. The settings you used are correct but did you resize the images to 256? Also, for the experiments on BUSI dataset, we only considered the benign and mailgnant images resulting in a total of 647 images.
> 
> i have resized the images to 256 by the train_transform and val_transform acording to your source code. Busi dataset is also downloaded following the [link](https://www.kaggle.com/aryashah2k/breast-ultrasound-images-dataset) you provided. And then put the 647 images in the inputs/busi/images and put the 647 masks in the inputs/busi/masks/0

**Comment by xiaohancl** [comment]
> > > 你好@xiaohancl，我刚刚重新检查，我能够得到论文中报告的性能。您使用的设置是正确的，但您是否将图像大小调整为 256？此外，对于 BUSI 数据集的实验，我们只考虑了良性和恶性图像，总共有 647 幅图像。
> > 
> > 
> > 我已根据您的源代码通过 train_transform 和 val_transform 将图像大小调整为 256。Busi 数据集也可以通过您提供的[链接下载。](https://www.kaggle.com/aryashah2k/breast-ultrasound-images-dataset)然后将647张图片放入inputs/busi/images中，将647张mask放入inputs/busi/masks/0

**Comment by xiaohancl** [comment]
I have resized the images by train_transform and val_transform(Resize(256,256)).dataset is begin and maligant(total 647)

---Original---
From: "Jeya Maria ***@***.***&gt;
Date: Thu, Apr 28, 2022 01:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jeya-maria-jose/UNeXt-pytorch] Parameter Settings on BUSI dataset (Issue #12)




 
Hi @xiaohancl , I just rechecked and I am able to get the reported performance in the paper. The settings you used are correct but did you resize the images to 256? Also, for the experiments on BUSI dataset, we only considered the benign and mailgnant images resulting in a total of 647 images.
