### ISSUE TITLE
NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Eveinn** [jeya-maria-jose/UNeXt-pytorch#13]
how do i solve this problem
![图片](https://user-images.githubusercontent.com/76954487/164960711-c40c8719-af01-4032-9fd1-43443e367451.png)
`Traceback (most recent call last):
  File "D:/Code/UNeXt/train.py", line 371, in <module>
    main()
  File "D:/Code/UNeXt/train.py", line 326, in main
    train_log = train(config, train_loader, model, criterion, optimizer)
  File "D:/Code/UNeXt/train.py", line 119, in train
    for input, target, _ in train_loader:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\UNeXt\dataset.py", line 63, in __getitem__
    img_id + self.mask_ext), cv2.IMREAD_GRAYSCALE)[..., None])
TypeError: 'NoneType' object is not subscriptable
  0%|          | 0/21 [00:00<?, ?it/s]`

**Comment by jeya-maria-jose** [comment]
I believe this has something to do with the input type (3 channel or 1 channel) option. Can you please post the command line you used in terminal?

**Comment by Eveinn** [comment]
> --name
UNEXT-BUSI
--dataset
BUSI
--img_ext
.png
--mask_ext
.png
--lr
0.0001
--epochs
500
--input_w
449
--input_h
598
--b
8
--epochs
1000
--input_channels
1

BTW,I have changed the number of  input_channels(both 1 channel and 3 channels had done，and failed)

**Comment by Eveinn** [comment]
--name
UNEXT-pf
--dataset
BUSI
--img_ext
.png
--mask_ext
.png
--lr
0.0001
--epochs
1000
--input_w
512
--input_h
512
--b
8

**Comment by huying12** [comment]
Have you solved this problem？

**Comment by Chikeee** [comment]
The file names of the images and labels must be the same.

**Comment by Eveinn** [comment]
> The file names of the images and labels must be the same.

they are same

**Comment by Chikeee** [comment]
> > The file names of the images and labels must be the same.
> 
> they are same
You can give me the email and I'll send you my code

**Comment by huying12** [comment]
I have changed the image and mask name to be consistent, but it still appears TypeError: Caught TypeError in DataLoader worker process 0 and TypeError: 'NoneType' object is not subscriptable.Can you help me solve this problem? Thank you very much.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeya-maria-jose/UNeXt-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 晚上8:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeya-maria-jose/UNeXt-pytorch] NoneType' object is not subscriptable (Issue #13)





  
The file names of the images and labels must be the same.
  
they are same

**Comment by Eveinn** [comment]
> > > The file names of the images and labels must be the same.
> > 
> > 
> > they are same
> > You can give me the email and I'll send you my code

yinwen325@163.com.Thanks!

**Comment by Chikeee** [comment]
> > > > The file names of the images and labels must be the same.
> > > 
> > > 
> > > they are same
> > > You can give me the email and I'll send you my code
> 
> [yinwen325@163.com.Thanks](mailto:yinwen325@163.com.Thanks)!

I have sent the code to your email.

**Comment by CJD1203** [comment]
> I have changed the image and mask name to be consistent, but it still appears TypeError: Caught TypeError in DataLoader worker process 0 and TypeError: 'NoneType' object is not subscriptable.Can you help me solve this problem? Thank you very much.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jeya-maria-jose/UNeXt-pytorch" ***@***.***&gt;; 发送时间:&nbsp;2022年5月16日(星期一) 晚上8:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jeya-maria-jose/UNeXt-pytorch] NoneType' object is not subscriptable (Issue #13) The file names of the images and labels must be the same. they are same — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;



> I have changed the image and mask name to be consistent, but it still appears TypeError: Caught TypeError in DataLoader worker process 0 and TypeError: 'NoneType' object is not subscriptable.Can you help me solve this problem? Thank you very much.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jeya-maria-jose/UNeXt-pytorch" ***@***.***&gt;; 发送时间:&nbsp;2022年5月16日(星期一) 晚上8:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jeya-maria-jose/UNeXt-pytorch] NoneType' object is not subscriptable (Issue #13) The file names of the images and labels must be the same. they are same — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Hello, I have encountered this problem too. Have you solved it?

> I have changed the image and mask name to be consistent, but it still appears TypeError: Caught TypeError in DataLoader worker process 0 and TypeError: 'NoneType' object is not subscriptable.Can you help me solve this problem? Thank you very much.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jeya-maria-jose/UNeXt-pytorch" ***@***.***&gt;; 发送时间:&nbsp;2022年5月16日(星期一) 晚上8:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jeya-maria-jose/UNeXt-pytorch] NoneType' object is not subscriptable (Issue #13) The file names of the images and labels must be the same. they are same — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Hello, I have encountered this problem too. Have you solved it?

**Comment by CJD1203** [comment]
> > > > > The file names of the images and labels must be the same.
> > > > 
> > > > 
> > > > they are same
> > > > You can give me the email and I'll send you my code
> > 
> > 
> > [yinwen325@163.com.Thanks](mailto:yinwen325@163.com.Thanks)!
> 
> I have sent the code to your email.

hi，could you please send me the code too, thanks!  my email: welcomcjd@163.com

**Comment by Sweetnehi** [comment]
> 图像和标签的文件名必须相同。

Can you send me the code to my email? Thanks
2576749829@qq.com

**Comment by Zzs0720** [comment]
> > > 图像和标签的文件名必须相同。
> > 
> > 
> > 他们是一样的你可以给我电子邮件，我会给你我的代码

could you please send me the code too, thanks! 
email: 1097575240@qq.com

**Comment by huying12** [comment]
I have changed the image and mask name to be consistent, but it still appears TypeError: Caught TypeError in DataLoader worker process 0 and TypeError: 'NoneType' object is not subscriptable.Can you help me solve this problem? Thank you very much.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeya-maria-jose/UNeXt-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 晚上8:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeya-maria-jose/UNeXt-pytorch] NoneType' object is not subscriptable (Issue #13)





 
The file names of the images and labels must be the same.

**Comment by SE-Nickjackson** [comment]
> > > > 图像和标签的文件名必须相同。
> > > 
> > > 
> > > 他们是一样的你可以给我电子邮件，我会给你我的代码
> 
> could you please send me the code too, thanks! email: [1097575240@qq.com](mailto:1097575240@qq.com)

 could you please send me the code too, thanks! email: caifls@163.com

**Comment by SE-Nickjackson** [comment]
> could you please send me the code too, thanks! email: [caifls@163.com](mailto:caifls@163.com)

could you please send me the code too, thanks! email: [caifls@163.com](mailto:caifls@163.com)

**Comment by RacusNguyen** [comment]
> > > > > The file names of the images and labels must be the same.
> > > > 
> > > > 
> > > > they are same
> > > > You can give me the email and I'll send you my code
> > 
> > 
> > [yinwen325@163.com.Thanks](mailto:yinwen325@163.com.Thanks)!
> 
> I have sent the code to your email.

could you please send me the code too. my email: ducnt.hust.edu@gmail.com . thanks!

**Comment by Myrrolinz** [comment]
> > > > > The file names of the images and labels must be the same.
> > > > 
> > > > 
> > > > they are same
> > > > You can give me the email and I'll send you my code
> > 
> > 
> > [yinwen325@163.com.Thanks](mailto:yinwen325@163.com.Thanks)!
> 
> I have sent the code to your email.

Hi, I still have the same problem. Could you send me a copy? 1195564913@qq.com, thanks!

**Comment by zxq-clt** [comment]
The file names of the images and labels must be the same.

they are same
You can give me the email and I'll send you my code

[yinwen325@163.com.Thanks](mailto:yinwen325@163.com.Thanks)!

I have sent the code to your email.

Hi, I still have the same problem. Could you send me a copy? 2496453454@qq.com, thanks!
