### ISSUE TITLE
Incorrect usage of Normalize in transforms

### ISSUE THREAD

**Issue by david-stojanovski** [jeya-maria-jose/UNeXt-pytorch#22]
I found a bug:

You use the albumentations.augmentations  transforms function to normalize the input images, however it uses some random values which are not the actual mean and standard deviations of the data sets. You would have to calculate the mean and standard deviation of the data set beforehand and input them as values for it to be correct. Not the end of the world, but would probably help in stability and overall performance to correct this.

**Comment by jeya-maria-jose** [comment]
Agreed. Thanks for pointing it out. The right way would be to calculate them for the specific dataset the network is trained on.
