### ISSUE TITLE
The shifted MLP operation in the code seems to be different from what the paper says. Can you help me?

### ISSUE THREAD

**Issue by yangliu1510** [jeya-maria-jose/UNeXt-pytorch#27]
From the code the shifted mlp operation seems a bit like the operation in [S2-MLP: Spatial-Shift MLP Architecture for Vision].

**Comment by sdtegaotian** [comment]
yes,I think so

**Comment by chi-sq** [comment]
yes,it totally different.I don't how shifted operation pays attention to the local as the paper illustrate. I wonder if my understanding is right.

**Comment by jeya-maria-jose** [comment]
The shift operation restricts the information that the MLP sees. Shifting across height and width simply localizes the span of information that the network sees.
