### ISSUE TITLE
self.img_ids = img_ids

### ISSUE THREAD

**Issue by antoniaaaaaaaaaaaa** [jeya-maria-jose/UNeXt-pytorch#3]
self.img_ids = img_ids
self.img_dir =img_dir
self.mask_dir = mask_dir
self.img_ext = '.png'
self.mask_ext = '.png'
self.num_classes = 2
 self.transform = transform

self.img_ids = img_ids
self.img_dir =img_dir
self.mask_dir = mask_dir

Here is how the equals sign should be written, and the first one is not in the form of a list Can you give an example?

**Comment by jeya-maria-jose** [comment]
We get the list in the main train code https://github.com/jeya-maria-jose/UNeXt-pytorch/blob/076937f1f0161f4baf8ffb5f2948ac67f93afe29/train.py#L251.
