### ISSUE TITLE
The shift function is not used

### ISSUE THREAD

**Issue by raozhongyu** [jeya-maria-jose/UNeXt-pytorch#4]
Thanks for your great work, I notice that the function of shift in archs.py is not  used.

**Comment by jeya-maria-jose** [comment]
Thank you for your observation. Yes, instead of calling the function; I just wrote it inside the forward function https://github.com/jeya-maria-jose/UNeXt-pytorch/blob/076937f1f0161f4baf8ffb5f2948ac67f93afe29/archs.py#L83. Sorry about that. Will comment out the function.
