### ISSUE TITLE
Performance on multi-class segmentation. 

### ISSUE THREAD

**Issue by Capchenxi** [jeya-maria-jose/UNeXt-pytorch#8]
Hello, 
Thanks for your excellent idea on shifted mlp module. I have some questions on other segmentation task other than the medical segmentation. 
I noticed that the code you provide is mainly focusing on 2-class segmentation task. Is there any possible that you tried the UneXt structure on multi-class task like Cityscapes? I have tried this structure on my own task, which is a 12-class segmentation task for parking lot scene, but it performs poorly. So I just wonder if the UneXt is experimented on Cityscape dataset or other multi-class dataset and how it performs? Thanks.

**Comment by jeya-maria-jose** [comment]
Hi, I have not experimented UNext with Cityscapes. My guess is that we might need more representative power to work on more complex datasets.

**Comment by Capchenxi** [comment]
> Hi, I have not experimented UNext with Cityscapes. My guess is that we might need more representative power to work on more complex datasets.

Thanks for your prompt reply. I'm now trying to change the backbone of unext into other complex structures. Hope it helps.
